--[[function start ()
registerObjectName("Stone")
stone = createObject("stone", 2.6,0.1,-1.7, "gray")
say(getTop())
setRotation(stone, 0.7853983, 0.7853982, 0.7853982)
setScale(stone, 0.3, 0.3, 0.3)

registerObjectName("TreeStem")
treestem = createObject("treestem", 3.6,0.5,-2.5, "brown")
say(getTop())
setRotation(treestem, 0, 0, 0)
setScale(treestem, 0.5, 1, 0.5)

registerObjectName("TreeLeaves")
treeleaves = createObject("treeleaves", 3.6,1.7,-2.5, "ltgreen")
say(getTop())
setRotation(treeleaves, 0, 0, 0)
setScale(treeleaves, 1.5, 1.5, 1.5)

registerObjectName("HouseWallNorth")
housewallnorth = createObject("housewallnorth", -3.2,0.6,3.2, "gray")
say(getTop())
setRotation(housewallnorth, 0, 0, 0)
setScale(housewallnorth, 3, 1.5, 0.2)

registerObjectName("HouseWallSouthEast")
housewallsoutheast = createObject("housewallsoutheast", -2.4,0.6,1.2, "gray")
say(getTop())
setRotation(housewallsoutheast, 0, 0, 0)
setScale(housewallsoutheast, 1.2, 1.5, 0.2)

registerObjectName("HouseWallEast")
housewalleast = createObject("housewalleast", -1.8,0.6,2.2, "gray")
say(getTop())
setRotation(housewalleast, 0, 0, 0)
setScale(housewalleast, 0.2, 1.5, 2.2)

registerObjectName("HouseWallWest")
housewallwest = createObject("housewallwest", -4.6,0.6,2.2, "gray")
say(getTop())
setRotation(housewallwest, 0, 0, 0)
setScale(housewallwest, 0.2, 1.5, 2.2)

registerObjectName("HouseWallSouthWest")
housewallsouthwest = createObject("housewallsouthwest", -4.2,0.6,1.2, "gray")
say(getTop())
setRotation(housewallsouthwest, 0, 0, 0)
setScale(housewallsouthwest, 0.7, 1.5, 0.2)

registerObjectName("HouseDoor")
housedoor = createObject("housedoor", -3.4,0.6,1.2, "brown")
say(getTop())
setRotation(housedoor, 0, 0, 0)
setScale(housedoor, 0.7, 1.5, 0.2)

registerObjectName("TownSquare")
townsquare = createObject("townsquare", 0,0,0, "green")
say(getTop())
setRotation(townsquare, 0, 0, 0)
setScale(townsquare, 10, 0, 7.5)

registerObjectName("HouseWallNorth")
housewallnorth = createObject("housewallnorth", 3,0.6,3.2, "gray")
say(getTop())
setRotation(housewallnorth, 0, 0, 0)
setScale(housewallnorth, 3, 1.5, 0.2)

registerObjectName("HouseWallSouthEast")
housewallsoutheast = createObject("housewallsoutheast", 4,0.6,1.2, "gray")
say(getTop())
setRotation(housewallsoutheast, 0, 0, 0)
setScale(housewallsoutheast, 1, 1.5, 0.2)

registerObjectName("HouseWallEast")
housewalleast = createObject("housewalleast", 4.4,0.6,2.2, "gray")
say(getTop())
setRotation(housewalleast, 0, 0, 0)
setScale(housewalleast, 0.2, 1.5, 2.2)

registerObjectName("HouseWallWest")
housewallwest = createObject("housewallwest", 1.7,0.6,2.2, "gray")
say(getTop())
setRotation(housewallwest, 0, 0, 0)
setScale(housewallwest, 0.2, 1.5, 2.2)

registerObjectName("HouseWallSouthWest")
housewallsouthwest = createObject("housewallsouthwest", 2.2,0.6,1.2, "gray")
say(getTop())
setRotation(housewallsouthwest, 0, 0, 0)
setScale(housewallsouthwest, 1, 1.5, 0.2)

registerObjectName("Lever")
lever = createObject("lever", -1.2,0.4,-3.3, "yellow")
say(getTop())
setRotation(lever, 0, 0, 0.2796017)
setScale(lever, 0.5, 0.7, 0.7)

registerObjectName("Gate")
gate = createObject("gate", 0,1,-3.8, "brown")
say(getTop())
setRotation(gate, 0, 0, 0)
setScale(gate, 1.2, 2, 0.3)

registerObjectName("Gold")
gold = createObject("gold", -4.2,0.1,2.8, "yellow")
say(getTop())
setRotation(gold, 0, 0, 0)
setScale(gold, 0.3, 0.3, 0.3)

registerObjectName("Key")
key = createObject("key", -4.7,0.1,-3.4, "yellow")
say(getTop())
setRotation(key, 0, 0, 0)
setScale(key, 0.3, 0.3, 0.3)

registerObjectName("NPC")
npc = createObject("npc", 2.2,0.4,2.7, "brown")
say(getTop())
setRotation(npc, 0, 0, 0)
setScale(npc, 0.5, 1, 0.5)


end]]--